import { ConflictException,Injectable,UnauthorizedException } from '@nestjs/common'; import { JwtService } from '@nestjs/jwt'; import { PrismaService } from '../prisma/prisma.service'; import { ForgotPasswordDto,LoginDto,RegisterDto,ResetPasswordDto } from './dto'; import * as bcrypt from 'bcrypt'; import { createHash,randomBytes } from 'crypto';
@Injectable() export class AuthService{constructor(private prisma:PrismaService,private jwt:JwtService){}
 private hashToken(v:string){return createHash('sha256').update(v).digest('hex')}
 private async access(user:{id:string;email:string;role:any}){return this.jwt.signAsync({sub:user.id,email:user.email,role:user.role},{secret:process.env.JWT_ACCESS_SECRET,expiresIn:(process.env.ACCESS_TOKEN_TTL||'15m') as any})}
 private async refresh(user:{id:string;email:string;role:any}){const raw=await this.jwt.signAsync({sub:user.id,type:'refresh'},{secret:process.env.JWT_REFRESH_SECRET,expiresIn:`${Number(process.env.REFRESH_TOKEN_DAYS||7)}d` as any}); await this.prisma.refreshToken.create({data:{userId:user.id,tokenHash:this.hashToken(raw),expiresAt:new Date(Date.now()+Number(process.env.REFRESH_TOKEN_DAYS||7)*86400000)}}); return raw}
 async register(dto:RegisterDto){const email=dto.email.toLowerCase().trim(); if(await this.prisma.user.findUnique({where:{email}}))throw new ConflictException('E-mail já cadastrado'); const user=await this.prisma.user.create({data:{name:dto.name.trim(),email,passwordHash:await bcrypt.hash(dto.password,12),phone:dto.phone,whatsapp:dto.whatsapp,city:dto.city,state:dto.state?.toUpperCase()}}); return {user:{id:user.id,name:user.name,email:user.email,role:user.role},accessToken:await this.access(user),refreshToken:await this.refresh(user)}}
 async login(dto:LoginDto){const user=await this.prisma.user.findUnique({where:{email:dto.email.toLowerCase().trim()}}); if(!user||user.status!=='ACTIVE'||!await bcrypt.compare(dto.password,user.passwordHash))throw new UnauthorizedException('Credenciais inválidas'); return {user:{id:user.id,name:user.name,email:user.email,role:user.role},accessToken:await this.access(user),refreshToken:await this.refresh(user)}}
 async renew(raw:string){try{const payload=await this.jwt.verifyAsync(raw,{secret:process.env.JWT_REFRESH_SECRET}); const found=await this.prisma.refreshToken.findUnique({where:{tokenHash:this.hashToken(raw)},include:{user:true}}); if(!found||found.revokedAt||found.expiresAt<new Date()||found.user.status!=='ACTIVE'||found.userId!==payload.sub)throw new Error(); await this.prisma.refreshToken.update({where:{id:found.id},data:{revokedAt:new Date()}}); return {accessToken:await this.access(found.user),refreshToken:await this.refresh(found.user),user:{id:found.user.id,name:found.user.name,email:found.user.email,role:found.user.role}}}catch{throw new UnauthorizedException('Refresh token inválido')}}
 async logout(raw?:string){if(raw){const token=await this.prisma.refreshToken.findUnique({where:{tokenHash:this.hashToken(raw)}}); if(token&&!token.revokedAt)await this.prisma.refreshToken.update({where:{id:token.id},data:{revokedAt:new Date()}})} return {message:'Sessão encerrada'}}
 async forgot(dto:ForgotPasswordDto){const user=await this.prisma.user.findUnique({where:{email:dto.email.toLowerCase().trim()}}); if(!user)return {message:'Se o e-mail estiver cadastrado, as instruções serão enviadas.'}; const raw=randomBytes(32).toString('hex'); await this.prisma.passwordResetToken.create({data:{userId:user.id,tokenHash:this.hashToken(raw),expiresAt:new Date(Date.now()+30*60000)}}); return process.env.NODE_ENV==='production'?{message:'Se o e-mail estiver cadastrado, as instruções serão enviadas.'}:{message:'Token de desenvolvimento gerado.',resetToken:raw}}
 async reset(dto:ResetPasswordDto){const token=await this.prisma.passwordResetToken.findUnique({where:{tokenHash:this.hashToken(dto.token)}}); if(!token||token.usedAt||token.expiresAt<new Date())throw new UnauthorizedException('Token inválido ou expirado'); await this.prisma.$transaction([this.prisma.user.update({where:{id:token.userId},data:{passwordHash:await bcrypt.hash(dto.password,12)}}),this.prisma.passwordResetToken.update({where:{id:token.id},data:{usedAt:new Date()}}),this.prisma.refreshToken.updateMany({where:{userId:token.userId,revokedAt:null},data:{revokedAt:new Date()}})]); return {message:'Senha alterada com sucesso'}} }
