import { ForbiddenException,Injectable,NotFoundException } from '@nestjs/common'; import { Prisma,Situation } from '@prisma/client'; import { PrismaService } from '../prisma/prisma.service'; import { AnimalQueryDto,CreateAnimalDto,UpdateAnimalDto } from './dto';
@Injectable() export class AnimalsService{constructor(private prisma:PrismaService){} async list(q:AnimalQueryDto){const page=Math.max(Number(q.page)||1,1),limit=Math.min(Math.max(Number(q.limit)||12,1),50); const where:Prisma.AnimalWhereInput={}; if(q.situation)where.situation=q.situation; if(q.species)where.species={contains:q.species,mode:'insensitive'}; if(q.city)where.city={contains:q.city,mode:'insensitive'}; if(q.neighborhood)where.neighborhood={contains:q.neighborhood,mode:'insensitive'}; if(q.breed)where.breed={contains:q.breed,mode:'insensitive'}; if(q.color)where.color={contains:q.color,mode:'insensitive'}; if(q.sex)where.sex=q.sex;if(q.size)where.size=q.size;if(q.q)where.OR=[{name:{contains:q.q,mode:'insensitive'}},{species:{contains:q.q,mode:'insensitive'}},{breed:{contains:q.q,mode:'insensitive'}},{color:{contains:q.q,mode:'insensitive'}},{description:{contains:q.q,mode:'insensitive'}}]; const [data,total]=await this.prisma.$transaction([this.prisma.animal.findMany({where,include:{images:true},orderBy:{createdAt:'desc'},skip:(page-1)*limit,take:limit}),this.prisma.animal.count({where})]);return {data,total,page,limit,pages:Math.max(Math.ceil(total/limit),1)}}
 async one(id:string){const a=await this.prisma.animal.findUnique({where:{id},include:{images:true,owner:{select:{id:true,name:true}},sightings:{include:{reporter:{select:{name:true}}},orderBy:{createdAt:'desc'}}}});if(!a)throw new NotFoundException('Animal não encontrado');return a}
 async mine(userId:string){return this.prisma.animal.findMany({where:{ownerId:userId},include:{images:true,_count:{select:{sightings:true}}},orderBy:{createdAt:'desc'}})}
 async create(dto:CreateAnimalDto,userId:string,files:Express.Multer.File[]=[]){const {occurrenceDate,latitude,longitude,...rest}=dto;return this.prisma.animal.create({data:{...rest,state:dto.state.toUpperCase(),occurrenceDate:new Date(occurrenceDate),latitude:latitude===undefined?undefined:new Prisma.Decimal(latitude),longitude:longitude===undefined?undefined:new Prisma.Decimal(longitude),ownerId:userId,images:{create:files.map(f=>({url:`/uploads/${f.filename}`}))}},include:{images:true}})}
 private async can(id:string,userId:string,role:string){const a=await this.prisma.animal.findUnique({where:{id}});if(!a)throw new NotFoundException('Animal não encontrado');if(a.ownerId!==userId&&role!=='ADMIN')throw new ForbiddenException('Você não pode alterar este anúncio');return a}
 async update(id:string,dto:UpdateAnimalDto,userId:string,role:string){await this.can(id,userId,role);const {occurrenceDate,latitude,longitude,...rest}=dto;return this.prisma.animal.update({where:{id},data:{...rest,state:dto.state?.toUpperCase(),occurrenceDate:occurrenceDate?new Date(occurrenceDate):undefined,latitude:latitude===undefined?undefined:new Prisma.Decimal(latitude),longitude:longitude===undefined?undefined:new Prisma.Decimal(longitude)}})}
 async status(id:string,situation:Situation,userId:string,role:string){await this.can(id,userId,role);return this.prisma.animal.update({where:{id},data:{situation}})}
 async remove(id:string,userId:string,role:string){await this.can(id,userId,role);await this.prisma.animal.update({where:{id},data:{situation:Situation.CLOSED}});return {message:'Anúncio encerrado'}} }
